BEGIN TRANSACTION

--LAST UPDATED: 03/18/2022.
--You should probably make sure that the column lists and tables referenced are correct

--This script restores a Kempe/Parent Survey/FROG that was deleted.
--NOTE: This does NOT restore deleted attachments.  Can't do it since it will have been deleted from Azure storage.

--Instructions:
--1. Set the PC1ID variable to the correct value.
--2. Make sure the last line of the script is 'ROLLBACK'.
--3. Run the script and make sure there are no errors or unexpected results.
--4. If everything looks good, change 'ROLLBACK' to 'COMMIT'
--5. Run the script.
--6. IMMEDIATELY change 'COMMIT' to 'ROLLBACK'.  This helps prevent accidentally running the script twice.
--7. Check the case on the MIS to see if you can open the Kempe/Parent Survey/FROG. Make sure everything on the form in the MIS looks correct.

--Declare the necessary variables
DECLARE @PC1ID VARCHAR(13) = ''
DECLARE @HVCaseFK INT = (SELECT TOP(1) hvcasefk FROM dbo.CaseProgram cp WHERE cp.PC1ID = @PC1ID ORDER BY cp.CaseProgramPK DESC)
DECLARE @ProgramFK INT = (SELECT TOP(1) cp.ProgramFK FROM dbo.CaseProgram cp WHERE cp.PC1ID = @PC1ID ORDER BY cp.CaseProgramPK DESC)
DECLARE @IsProgramOneStep BIT = (SELECT TOP(1) pos.IsOneStep FROM dbo.ProgramOneStep pos WHERE pos.ProgramFK = @ProgramFK ORDER BY pos.ProgramOneStepPK DESC)

DECLARE @OldPC1IssuesPK INT, @NewPC1IssuesPK INT, @HITSDeletedPK INT, @AuditCDeletedPK INT, @PHQ9DeletedPK INT, @CommonAttributesDeletedPK INT, @KempeDeletedPK INT, @OldKempePK INT, @NewKempePK INT

SET @KempeDeletedPK = (SELECT TOP(1) kd.KempeDeletedPK FROM dbo.KempeDeleted kd WHERE kd.HVCaseFK = @HVCaseFK ORDER BY kd.KempeDeletedPK DESC)
SET @OldKempePK = (SELECT TOP(1) kd.KempePK FROM dbo.KempeDeleted kd WHERE kd.KempeDeletedPK = @KempeDeletedPK ORDER BY kd.KempeDeletedPK DESC)
SET @OldPC1IssuesPK = (SELECT TOP(1) kd.PC1IssuesFK FROM dbo.KempeDeleted kd WHERE kd.KempeDeletedPK = @KempeDeletedPK ORDER BY kd.KempeDeletedPK DESC)
SET @HITSDeletedPK = (SELECT TOP(1) hd.HITSDeletedPK FROM dbo.HITSDeleted hd WHERE hd.HVCaseFK = @HVCaseFK AND hd.FormFK = @OldKempePK ORDER BY hd.HITSDeletedPK DESC)
SET @AuditCDeletedPK = (SELECT TOP(1) acd.AuditCDeletedPK FROM dbo.AuditCDeleted acd WHERE acd.HVCaseFK = @HVCaseFK AND acd.FormFK = @OldKempePK ORDER BY acd.AuditCDeletedPK DESC)
SET @PHQ9DeletedPK = (SELECT TOP(1) pd.PHQ9DeletedPK FROM dbo.PHQ9Deleted pd WHERE pd.HVCaseFK = @HVCaseFK AND pd.FormFK = @OldKempePK ORDER BY pd.PHQ9DeletedPK DESC)
SET @CommonAttributesDeletedPK = (SELECT TOP(1) cad.CommonAttributesDeletedPK FROM dbo.CommonAttributesDeleted cad WHERE cad.HVCaseFK = @HVCaseFK AND cad.FormFK = @OldKempePK ORDER BY cad.CommonAttributesDeletedPK DESC)

--Display the deleted rows
--Look over the deleted rows and make sure everything makes sense before changing ROLLBACK to COMMIT
SELECT * FROM dbo.HITSDeleted hd WHERE hd.HVCaseFK = @HVCaseFK
SELECT * FROM dbo.AuditCDeleted acd WHERE acd.HVCaseFK = @HVCaseFK
SELECT * FROM dbo.PHQ9Deleted pd WHERE pd.HVCaseFK = @HVCaseFK
SELECT * FROM dbo.CommonAttributesDeleted cad WHERE cad.HVCaseFK = @HVCaseFK
SELECT * FROM dbo.PC1IssuesDeleted pid WHERE pid.HVCaseFK = @HVCaseFK
SELECT * FROM dbo.KempeDeleted kd WHERE kd.HVCaseFK = @HVCaseFK

--Display the PK variables
--Check these against the select statements above to ensure they match
SELECT @KempeDeletedPK AS KempeDeletedPK, @OldPC1IssuesPK AS OldPC1IssuesPK, @HITSDeletedPK AS HITSDeletedPK, @AuditCDeletedPK AS AuditCDeletedPK, @PHQ9DeletedPK AS PHQ9DeletedPK, @CommonAttributesDeletedPK AS CommonAttributesDeletedPK

--If the program is NOT one-step, update the case progress
IF @IsProgramOneStep = 0
BEGIN

	UPDATE dbo.HVCase SET CaseProgress = '5.0' WHERE HVCasePK = @HVCaseFK

end

--Restore the PC1Issues row
INSERT INTO dbo.PC1Issues
(
    AlcoholAbuse,
    CriminalActivity,
    Depression,
    DevelopmentalDisability,
    DomesticViolence,
    FinancialDifficulty,
    Homeless,
    HVCaseFK,
    InadequateBasics,
    Interval,
    MaritalProblems,
    MentalIllness,
    OtherIssue,
    OtherIssueSpecify,
    OtherLegalProblems,
    PC1IssuesCreateDate,
    PC1IssuesCreator,
    PC1IssuesDate,
    PC1IssuesEditDate,
    PC1IssuesEditor,
    PC1IssuesPK_old,
    PhysicalDisability,
    ProgramFK,
    Smoking,
    SocialIsolation,
    Stress,
    SubstanceAbuse
)
SELECT 
    AlcoholAbuse,
    CriminalActivity,
    Depression,
    DevelopmentalDisability,
    DomesticViolence,
    FinancialDifficulty,
    Homeless,
    HVCaseFK,
    InadequateBasics,
    Interval,
    MaritalProblems,
    MentalIllness,
    OtherIssue,
    OtherIssueSpecify,
    OtherLegalProblems,
    PC1IssuesCreateDate,
    PC1IssuesCreator,
    PC1IssuesDate,
    PC1IssuesEditDate,
    PC1IssuesEditor,
    PC1IssuesPK_old,
    PhysicalDisability,
    ProgramFK,
    Smoking,
    SocialIsolation,
    Stress,
    SubstanceAbuse
FROM dbo.PC1IssuesDeleted pid 
WHERE pid.PC1IssuesPK = @OldPC1IssuesPK

--Get the new PC1IssuesPK for the Kempe row
SET @NewPC1IssuesPK = (SELECT TOP(1) pi.PC1IssuesPK FROM dbo.PC1Issues pi WHERE pi.HVCaseFK = @HVCaseFK ORDER BY pi.PC1IssuesPK DESC)

--Restore the Kempe row with the new PC1IssuesPK
INSERT INTO dbo.Kempe
(
    DadBondingArea,
    DadChildHistoryArea,
    DadCPSArea,
    DadDisciplineArea,
    DadExpectationArea,
    DadPerceptionArea,
    DadSAMICHArea,
    DadScore,
    DadSelfEsteemArea,
    DadStressorArea,
    DadViolentArea,
    FAWFK,
    FOBPartnerPresent,
    FOBPresent,
    GrandParentPresent,
    HVCaseFK,
    KempeCreateDate,
    KempeCreator,
    KempeDate,
    KempeEditDate,
    KempeEditor,
    KempeResult,
    MOBPartnerPresent,
    MOBPresent,
    MomBondingArea,
    MomChildHistoryArea,
    MomCPSArea,
    MomDisciplineArea,
    MomExpectationArea,
    MomPerceptionArea,
    MomSAMICHArea,
    MomScore,
    MomSelfEsteemArea,
    MomStressorArea,
    MomViolentArea,
    NegativeReferral,
    OtherPresent,
    PartnerBondingArea,
    PartnerChildHistoryArea,
    PartnerCPSArea,
    PartnerDisciplineArea,
    PartnerExpectationArea,
    PartnerInHome,
    PartnerPerceptionArea,
    PartnerSAMICHArea,
    PartnerScore,
    PartnerSelfEsteemArea,
    PartnerStressorArea,
    PartnerViolentArea,
    PC1ABadChild,
    PC1ADifficultChild,
    PC1AEmotionalNeeds,
    PC1AHarsh,
    PC1ATemper,
    PC1AUnrealistic,
    PC1AUnwanted,
    PC1CANer,
    PC1Criminal,
    PC1FosterChild,
    PC1IssuesFK,
    PC1MentallyIll,
    PC1Neglected,
    PC1ParentSubAbuse,
    PC1PhysicallyAbused,
    PC1SexuallyAbused,
    PC1SubAbuse,
    PC1SuspectCANer,
    PresentSpecify,
    ProgramFK,
    SupervisorObservation,
    FROG_BH_PC1Score,
    FROG_BH_PC1Comments,
    FROG_BH_P2Score,
    FROG_BH_P2Comments,
    FROG_CPS_PC1Score,
    FROG_CPS_PC1Comments,
    FROG_CPS_P2Score,
    FROG_CPS_P2Comments,
    FROG_CSS_PC1Score,
    FROG_CSS_PC1Comments,
    FROG_CSS_P2Score,
    FROG_CSS_P2Comments,
    FROG_FE_PC1Score,
    FROG_FE_PC1Comments,
    FROG_FE_P2Score,
    FROG_FE_P2Comments,
    FROG_GSL_PC1Score,
    FROG_GSL_PC1Comments,
    FROG_GSL_P2Score,
    FROG_GSL_P2Comments,
    FROG_ICD_PC1Score,
    FROG_ICD_PC1Comments,
    FROG_ICD_P2Score,
    FROG_ICD_P2Comments,
    FROG_Introduction,
    FROG_IPCM_PC1Score,
    FROG_IPCM_PC1Comments,
    FROG_IPCM_P2Score,
    FROG_IPCM_P2Comments,
    FROG_IPS_PC1Score,
    FROG_IPS_PC1Comments,
    FROG_IPS_P2Score,
    FROG_IPS_P2Comments,
    FROG_IsFormFrog,
    FROG_MH_PC1Score,
    FROG_MH_PC1Comments,
    FROG_MH_P2Score,
    FROG_MH_P2Comments,
    FROG_PC_PC1Score,
    FROG_PC_PC1Comments,
    FROG_PC_P2Score,
    FROG_PC_P2Comments,
    FROG_PCE_PC1Score,
    FROG_PCE_PC1Comments,
    FROG_PCE_P2Score,
    FROG_PCE_P2Comments,
    FROG_PD_PC1Score,
    FROG_PD_PC1Comments,
    FROG_PD_P2Score,
    FROG_PD_P2Comments,
    FROG_P2IdentificationCode,
    FROG_P2Present,
    FROG_Referrals,
    FROG_SC_PC1Score,
    FROG_SC_PC1Comments,
    FROG_SC_P2Score,
    FROG_SC_P2Comments,
    FROG_SCE_PC1Score,
    FROG_SCE_PC1Comments,
    FROG_SCE_P2Score,
    FROG_SCE_P2Comments
)
SELECT 
    DadBondingArea,
    DadChildHistoryArea,
    DadCPSArea,
    DadDisciplineArea,
    DadExpectationArea,
    DadPerceptionArea,
    DadSAMICHArea,
    DadScore,
    DadSelfEsteemArea,
    DadStressorArea,
    DadViolentArea,
    FAWFK,
    FOBPartnerPresent,
    FOBPresent,
    GrandParentPresent,
    HVCaseFK,
    KempeCreateDate,
    KempeCreator,
    KempeDate,
    KempeEditDate,
    KempeEditor,
    KempeResult,
    MOBPartnerPresent,
    MOBPresent,
    MomBondingArea,
    MomChildHistoryArea,
    MomCPSArea,
    MomDisciplineArea,
    MomExpectationArea,
    MomPerceptionArea,
    MomSAMICHArea,
    MomScore,
    MomSelfEsteemArea,
    MomStressorArea,
    MomViolentArea,
    NegativeReferral,
    OtherPresent,
    PartnerBondingArea,
    PartnerChildHistoryArea,
    PartnerCPSArea,
    PartnerDisciplineArea,
    PartnerExpectationArea,
    PartnerInHome,
    PartnerPerceptionArea,
    PartnerSAMICHArea,
    PartnerScore,
    PartnerSelfEsteemArea,
    PartnerStressorArea,
    PartnerViolentArea,
    PC1ABadChild,
    PC1ADifficultChild,
    PC1AEmotionalNeeds,
    PC1AHarsh,
    PC1ATemper,
    PC1AUnrealistic,
    PC1AUnwanted,
    PC1CANer,
    PC1Criminal,
    PC1FosterChild,
    @NewPC1IssuesPK, --The new PK
    PC1MentallyIll,
    PC1Neglected,
    PC1ParentSubAbuse,
    PC1PhysicallyAbused,
    PC1SexuallyAbused,
    PC1SubAbuse,
    PC1SuspectCANer,
    PresentSpecify,
    ProgramFK,
    SupervisorObservation,
    FROG_BH_PC1Score,
    FROG_BH_PC1Comments,
    FROG_BH_P2Score,
    FROG_BH_P2Comments,
    FROG_CPS_PC1Score,
    FROG_CPS_PC1Comments,
    FROG_CPS_P2Score,
    FROG_CPS_P2Comments,
    FROG_CSS_PC1Score,
    FROG_CSS_PC1Comments,
    FROG_CSS_P2Score,
    FROG_CSS_P2Comments,
    FROG_FE_PC1Score,
    FROG_FE_PC1Comments,
    FROG_FE_P2Score,
    FROG_FE_P2Comments,
    FROG_GSL_PC1Score,
    FROG_GSL_PC1Comments,
    FROG_GSL_P2Score,
    FROG_GSL_P2Comments,
    FROG_ICD_PC1Score,
    FROG_ICD_PC1Comments,
    FROG_ICD_P2Score,
    FROG_ICD_P2Comments,
    FROG_Introduction,
    FROG_IPCM_PC1Score,
    FROG_IPCM_PC1Comments,
    FROG_IPCM_P2Score,
    FROG_IPCM_P2Comments,
    FROG_IPS_PC1Score,
    FROG_IPS_PC1Comments,
    FROG_IPS_P2Score,
    FROG_IPS_P2Comments,
    FROG_IsFormFrog,
    FROG_MH_PC1Score,
    FROG_MH_PC1Comments,
    FROG_MH_P2Score,
    FROG_MH_P2Comments,
    FROG_PC_PC1Score,
    FROG_PC_PC1Comments,
    FROG_PC_P2Score,
    FROG_PC_P2Comments,
    FROG_PCE_PC1Score,
    FROG_PCE_PC1Comments,
    FROG_PCE_P2Score,
    FROG_PCE_P2Comments,
    FROG_PD_PC1Score,
    FROG_PD_PC1Comments,
    FROG_PD_P2Score,
    FROG_PD_P2Comments,
    FROG_P2IdentificationCode,
    FROG_P2Present,
    FROG_Referrals,
    FROG_SC_PC1Score,
    FROG_SC_PC1Comments,
    FROG_SC_P2Score,
    FROG_SC_P2Comments,
    FROG_SCE_PC1Score,
    FROG_SCE_PC1Comments,
    FROG_SCE_P2Score,
    FROG_SCE_P2Comments
FROM dbo.KempeDeleted kd
WHERE kd.KempeDeletedPK = @KempeDeletedPK

--Get the new Kempe PK
SET @NewKempePK = (SELECT TOP(1) k.KempePK FROM dbo.Kempe k WHERE k.HVCaseFK = @HVCaseFK ORDER BY k.KempePK DESC)

--Restore the HITS row with the new Kempe PK
INSERT INTO dbo.HITS
(
    FormFK,
    FormInterval,
    FormType,
    HITSCreateDate,
    HITSCreator,
    HITSEditDate,
    HITSEditor,
    Hurt,
    HVCaseFK,
    Insult,
    Invalid,
    NotDoneReason,
    Positive,
    ProgramFK,
    Scream,
    Threaten,
    TotalScore,
    HITSDate,
    NotForPC1,
    WorkerFK
)
SELECT @NewKempePK, --The new PK
    FormInterval,
    FormType,
    HITSCreateDate,
    HITSCreator,
    HITSEditDate,
    HITSEditor,
    Hurt,
    HVCaseFK,
    Insult,
    Invalid,
    NotDoneReason,
    Positive,
    ProgramFK,
    Scream,
    Threaten,
    TotalScore,
    HITSDate,
    NotForPC1,
    WorkerFK
FROM dbo.HITSDeleted hd 
WHERE hd.HITSDeletedPK = @HITSDeletedPK

--Restore the AuditC row with the new Kempe PK
INSERT INTO dbo.AuditC
(
    AuditCCreateDate,
    AuditCCreator,
    AuditCEditDate,
    AuditCEditor,
    DailyDrinks,
    FormFK,
    FormInterval,
    FormType,
    HowOften,
    HVCaseFK,
    Invalid,
    MoreThanSix,
    Positive,
    ProgramFK,
    TotalScore,
    AuditCDate,
    NotForPC1,
    WorkerFK
)
SELECT 
    AuditCCreateDate,
    AuditCCreator,
    AuditCEditDate,
    AuditCEditor,
    DailyDrinks,
    @NewKempePK, --The new PK
    FormInterval,
    FormType,
    HowOften,
    HVCaseFK,
    Invalid,
    MoreThanSix,
    Positive,
    ProgramFK,
    TotalScore,
    AuditCDate,
    NotForPC1,
    WorkerFK
FROM dbo.AuditCDeleted acd 
WHERE acd.AuditCDeletedPK = @AuditCDeletedPK

--Restore the PHQ9 row with the new Kempe PK
INSERT INTO dbo.PHQ9
(
    Appetite,
    BadSelf,
    BetterOffDead,
    Concentration,
    DateAdministered,
    DepressionReferralMade,
    Difficulty,
    Down,
    FormFK,
    FormInterval,
    FormType,
    HVCaseFK,
    Interest,
    Invalid,
    ParticipantRefused,
    PHQ9CreateDate,
    PHQ9Creator,
    PHQ9EditDate,
    PHQ9Editor,
    Positive,
    ProgramFK,
    Sleep,
    SlowOrFast,
    Tired,
    TotalScore
)
SELECT 
    Appetite,
    BadSelf,
    BetterOffDead,
    Concentration,
    DateAdministered,
    DepressionReferralMade,
    Difficulty,
    Down,
    @NewKempePK, --The new PK
    FormInterval,
    FormType,
    HVCaseFK,
    Interest,
    Invalid,
    ParticipantRefused,
    PHQ9CreateDate,
    PHQ9Creator,
    PHQ9EditDate,
    PHQ9Editor,
    Positive,
    ProgramFK,
    Sleep,
    SlowOrFast,
    Tired,
    TotalScore
FROM dbo.PHQ9Deleted pd 
WHERE pd.PHQ9DeletedPK = @PHQ9DeletedPK

--Restore the CommonAttributes row with the new Kempe PK
INSERT INTO dbo.CommonAttributes
(
    AvailableMonthlyBenefits,
    AvailableMonthlyBenefitsUnknown,
    AvailableMonthlyIncome,
    CommonAttributesCreateDate,
    CommonAttributesCreator,
    CommonAttributesEditDate,
    CommonAttributesEditor,
    EducationalEnrollment,
    FormDate,
    FormFK,
    FormInterval,
    FormType,
    Gravida,
    HIFamilyChildHealthPlus,
    HighestGrade,
    HIMedicaidCaseNumber,
    HIOther,
    HIOtherSpecify,
    HIPCAP,
    HIPCAPCaseNumber,
    HIPrivate,
    HIUninsured,
    HIUnknown,
    HoursPerMonth,
    HVCaseFK,
    IsCurrentlyEmployed,
    LanguageSpecify,
    LivingArrangement,
    LivingArrangementSpecific,
    Looked4Employment,
    MaritalStatus,
    MonthlyIncomeUnknown,
    NumberEmployed,
    NumberInHouse,
    OBPInHome,
    OBPInvolvement,
    OBPInvolvementSpecify,
    Parity,
    PBEmergencyAssistance,
    PBEmergencyAssistanceAmount,
    PBFoodStamps,
    PBFoodStampsAmount,
    PBSSI,
    PBSSIAmount,
    PBTANF,
    PBTANFAmount,
    PBWIC,
    PBWICAmount,
    PC1HasMedicalProvider,
    PC1MedicalFacilityFK,
    PC1MedicalProviderFK,
    PC1ReceivingMedicaid,
    PCFK,
    PreviouslyEmployed,
    PrimaryLanguage,
    ProgramFK,
    ReceivingPreNatalCare,
    ReceivingPublicBenefits,
    SIDomesticViolence,
    SICPSACS,
    SIMentalHealth,
    SISubstanceAbuse,
    TANFServices,
    TANFServicesNo,
    TANFServicesNoSpecify,
    TCHasMedicalProvider,
    TCHIFamilyChildHealthPlus,
    TCHIMedicaidCaseNumber,
    TCHIPrivateInsurance,
    TCHIOther,
    TCHIOtherSpecify,
    TCHIUninsured,
    TCHIUnknown,
    TCMedicalCareSource,
    TCMedicalCareSourceOtherSpecify,
    TCMedicalFacilityFK,
    TCMedicalProviderFK,
    TCReceivingMedicaid,
    TimeBreastFed,
    WasBreastFed,
    WhyNotBreastFed
)
SELECT 
    AvailableMonthlyBenefits,
    AvailableMonthlyBenefitsUnknown,
    AvailableMonthlyIncome,
    CommonAttributesCreateDate,
    CommonAttributesCreator,
    CommonAttributesEditDate,
    CommonAttributesEditor,
    EducationalEnrollment,
    FormDate,
    @NewKempePK, --The new PK
    FormInterval,
    FormType,
    Gravida,
    HIFamilyChildHealthPlus,
    HighestGrade,
    HIMedicaidCaseNumber,
    HIOther,
    HIOtherSpecify,
    HIPCAP,
    HIPCAPCaseNumber,
    HIPrivate,
    HIUninsured,
    HIUnknown,
    HoursPerMonth,
    HVCaseFK,
    IsCurrentlyEmployed,
    LanguageSpecify,
    LivingArrangement,
    LivingArrangementSpecific,
    Looked4Employment,
    MaritalStatus,
    MonthlyIncomeUnknown,
    NumberEmployed,
    NumberInHouse,
    OBPInHome,
    OBPInvolvement,
    OBPInvolvementSpecify,
    Parity,
    PBEmergencyAssistance,
    PBEmergencyAssistanceAmount,
    PBFoodStamps,
    PBFoodStampsAmount,
    PBSSI,
    PBSSIAmount,
    PBTANF,
    PBTANFAmount,
    PBWIC,
    PBWICAmount,
    PC1HasMedicalProvider,
    PC1MedicalFacilityFK,
    PC1MedicalProviderFK,
    PC1ReceivingMedicaid,
    PCFK,
    PreviouslyEmployed,
    PrimaryLanguage,
    ProgramFK,
    ReceivingPreNatalCare,
    ReceivingPublicBenefits,
    SIDomesticViolence,
    SICPSACS,
    SIMentalHealth,
    SISubstanceAbuse,
    TANFServices,
    TANFServicesNo,
    TANFServicesNoSpecify,
    TCHasMedicalProvider,
    TCHIFamilyChildHealthPlus,
    TCHIMedicaidCaseNumber,
    TCHIPrivateInsurance,
    TCHIOther,
    TCHIOtherSpecify,
    TCHIUninsured,
    TCHIUnknown,
    TCMedicalCareSource,
    TCMedicalCareSourceOtherSpecify,
    TCMedicalFacilityFK,
    TCMedicalProviderFK,
    TCReceivingMedicaid,
    TimeBreastFed,
    WasBreastFed,
    WhyNotBreastFed
FROM dbo.CommonAttributesDeleted cad 
WHERE CommonAttributesDeletedPK = @CommonAttributesDeletedPK

ROLLBACK